const x = 10;

try {
  x = 2;
} catch (e) {
  console.log(`Erro: ${e}`);
}
